[project]
name = "poke-mobile"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cryptography>=44.0.0",
    "fastapi>=0.115.8",
    "pyjwt>=2.10.1",
    "requests>=2.32.3",
    "uvicorn>=0.34.0",
]
